config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  resources :sessions, only: [:new, :create, :destroy]

  # get 'users/new'
  resources :users, only: [:new, :create]

  # get 'contacts/index'
  #
  # get 'contacts/new'
  #
  # # get 'contacts/create'
  # post 'contacts/create'

  resources :contacts, only: [:index, :create, :new] # 컨트롤러 이름과 똑같이 만들면 됨

  get '/' => 'home#hello_world'
  get '/index' => 'home#index'
  get '/contact' => 'home#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # rails routes
  # Prefix Verb URIPattern(도메인 다음에 나오는 세부 도메인) Controller#Action 형태로 나온다.
  # (.:format) (생략할수도 있고 넣을수도 있다, format 정할 수 있다는 것).html .json format을 컨트롤러에서 받아서 처리 가능
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # ActiveRecord 상속 : ActiveRecord에서 제공하는 기능들을 쉽게 가져다 쓸 수 있다.
  # ActiveRecord덕분에 Rails모델은 실제 데이터베이스의 값을 쉽게 읽고 쓸 수 있게 된다.
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  # ApplicationRecord 상속
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper # 컨트롤러에서 헬퍼 사용하기 위함

  def authenticate
    # if !user_signed_in?
    #   redirect_to new_session_path
    # end
    # redirect_to new_session_path if !user_signed_in?
    redirect_to new_session_path unless user_signed_in?
  end

  def authenticate_admin
    unless current_user.admin
      flash[:alert] = 'no admin'
      redirect_to '/'
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate, only: [:index]
  before_action :authenticate_admin, only: [:index]
  def index
    @all_contacts = Contact.all # 배열 형태로 담기게 된다.
  end

  def new
  end

  def create
    @name = params[:name]
    @email = params[:email]
    @content = params[:content]

    new_contact = Contact.new(name: @name, email: @email, content: @content)
    if new_contact.save
      # save가 됐을 때 데이터베이스에 완전히 제대로 저장이 된다면 리턴값은 true,
      # save하는 과정에 문제가 생기게 되어서 실패하면 false를 리턴
      # redirect_to "/contacts/index"
      redirect_to contacts_path
    else
      # redirect_to "/contacts/new"
      redirect_to new_contact_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def hello_world
    # render text: '<h1>Hello World!</h1>'
    # render 'my_first_view'
  end

  def index
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email]) # 대소문자 구분 없이 : .downcase
    if user && user.authenticate(params[:password]) # text로 입력한 password를 해쉬값으로 바꿈
      # session[:user_id] = user.id
      log_in(user)
      redirect_to '/'
    else
      flash[:alert] = 'Invalid email/password combination'# flash에 메세지를 넣게 되면 다음 액션에서 호출해서 사용 가능
      redirect_to new_session_path
    end
  end

  def destroy
    log_out
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    User.create(email: params[:email],
                password: params[:password],
                password_confirmation: params[:password_confirmation],
                name: params[:name])
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    # if @current_user.nil?
    #   @current_user = User.find_by(id: session[:user_id])
    # end
    # @current_user = @current_user || User.find_by(id: session[:user_id])
    @current_user ||= User.find_by(id: session[:user_id])
    # return @current_user # 생략해도 무방함
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    # session[:user_id] = nil
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<!-- <h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

<p>name : <%#= @name %></p>
<p>email: <%#= @email %></p>
<p>content: <%#= @content %></p> -->

app/views/contacts/index.html.erb
<!-- <h1>Contacts#index</h1>
<p>Find me in app/views/contacts/index.html.erb</p> -->

<h1>All Contacts</h1>
<ul>
  <% @all_contacts.each do |contact| %>
    <li><%= contact.name %> : <%= contact.content %></li>
  <% end %>
</ul>

<!-- @all_contacts = [{name: 'juyeong', email: 'juyeong@gmail.com', content: 'hello world!'},
                      {name: 'john', email: 'john'....},
                      {name: '3333', email: ...}]-->

app/views/contacts/new.html.erb
<!-- <h1>Contacts#new</h1>
<p>Find me in app/views/contacts/new.html.erb</p> -->

<!-- <form action="/contacts/create" method="post"> -->
<%#= form_tag "/contacts/create", method: 'post' do %> <!-- form helper -->
<%= form_tag contacts_path, method: 'post' do %> <!-- 기본적으로 post 형태 -->
  <!-- get을 post로 바꾸게 되면 데이터들이 parameter가 주소에 바로 찍히지 않는다.
       게시판에 글쓰기같은 대량의 텍스트 같은 경우 get방식으로 그 양을 전체를 다 전달할 수 없지만 post방식이 되면 아무리 많은 텍스트라도 전달 가능 -->
  Name: <input type="text" name="name"><br>
  Email: <input type="email" name="email"><br>
  Content: <textarea name="content"></textarea><br>
  <input type="submit">
<% end %>
<!-- </form> -->

app/views/home/contact.html.erb
<h1>Contact Page</h1>
<%= image_tag('stone.png') %> <!-- helper -->

app/views/home/index.html.erb
<!-- partial을 불러오는 코드 -->
<h1>This is menu</h1>
<%= render partial: "shared/menu", locals: {title: "Menu1"} %> <!-- partial에 변수값을 넣어줘서 출력 -->
<%= render partial: "shared/menu", locals: {title: "Menu2"} %>
<%= render partial: "shared/menu" %> <!-- 언더바와 확장자 제외 -->

<div>
  2 곱하기 2는 <strong><%= 2 * 2 %></strong>
  2 곱하기 3은 <strong><%= "hi" %></strong>
</div>

<% if 1+2 == 2 %> <!-- 연산은 하되 출력은 안 함 -->
  <span>Correct!</span>
<% else %>
  <span>Wrong!</span>
<% end %>

<h1>김나박이</h1>
<% ["김범수", "나얼", "박효신", "이수"].each do |name| %>
  <span><%= name %></span>
<% end %>

<h1>현재시간</h1>
<span><%= DateTime.now %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- 모든 페이지에서 사용되는 글로벌 메뉴 -->
    <div id="global-header">
      <div class="container">
        <div class="logo">My Profile</div>
        <ul class="menu">
          <a href="/">
            <li class="item">Home</li>
          </a>
          <!-- <a href="/contact"> -->
          <!-- <a href="/contacts/new"> -->
          <%= link_to new_contact_path do %>
            <li class="item">Contact</li>
          <!-- </a> -->
          <% end %>
          <% if user_signed_in? %>
            <li class="item"><%= current_user.name %></li> <!-- view에서 모델을 호출하는 코드는 좋지 않다. -->
            <li class="item"><%= link_to 'Sign out', session_path(current_user), method: 'delete' %></li>
            <% if current_user.admin %>
              <li class="item"><%= link_to 'Contacts List', contacts_path %></li>
            <% end %>
          <% else %>
            <li class="item"><%= link_to 'Sign in', new_session_path %></li>
            <li class="item"><%= link_to 'Sign up', new_user_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div id="wrapper">
      <%= flash[:alert] %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_menu.html.erb
<!-- <p>shared menu : <%#= title %></p> -->
<p>shared menu : <%= local_assigns[:title] %></p>

app/views/users/new.html.erb
<!-- <h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p> -->

<h1>Sign up</h1>
<%= form_tag users_path do %>
  Email :
  <input type="email" name="email"><br>
  Password :
  <input type="password" name="password"><br>
  Password Confirmation :
  <input type="password" name="password_confirmation"><br>
  Name :
  <input type="text" name="name"><br>
  <input type="submit" value="Sign up">
<% end %>